version: '3.1'

networks:
  dvs-net:
    driver: bridge

services:
  container_name: dvs_rabbitmq
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    networks:
      - dvs-net
    environment:
      - RABBITMQ_PASSWORD=rabbitdvs
    restart: unless-stopped
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - /mnt/rabbitmq-persistence:/bitnami


  db:
    image: mysql:5.7
    container_name: mysql_dvs_5.7
    restart: always
    networks:
    - dvs-net
    environment:
      - MYSQL_DATABASE=basedvs
      - MYSQL_ROOT_PASSWORD=uN7yH@J1IfYJ4c%3s0Mqelj0wiz
      - MYSQL_USER=dvssqluser
      - MYSQL_PASSWORD=dvspassuser2019
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/data:/var/lib/mysql
      - /mnt/backup:/var/lib/backup
    ports:
      - "3306:3306"

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql:5.7
    volumes:
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_HOST=mysql_dvs_5.7
      - MYSQL_USER=root
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 16 * * *
    restart: unless-stopped

volumes:
  data: